import type { Tables, TablesInsert, TablesUpdate } from "./db/database.types.ts";

/**
 * ============================================================================
 * Database Entity Types
 * ============================================================================
 */

/**
 * Flashcard entity from the database.
 * Represents the complete flashcard row as stored in the database.
 */
export type FlashcardEntity = Tables<"flashcards">;

/**
 * ============================================================================
 * DTO (Data Transfer Objects) - API Response Types
 * ============================================================================
 */

/**
 * Flashcard DTO used in API responses.
 * Excludes internal fields (user_id, created_at, updated_at) that are not exposed to clients.
 * Derived from FlashcardEntity using Pick to select only public-facing fields.
 */
export type FlashcardDTO = Pick<FlashcardEntity, "id" | "source_text" | "translation">;

/**
 * Response for GET /api/flashcards - List all flashcards
 */
export interface ListFlashcardsResponse {
  data: FlashcardDTO[];
  count: number;
}

/**
 * Response for GET /api/flashcards/:id - Get single flashcard
 */
export interface GetFlashcardResponse {
  data: FlashcardDTO;
}

/**
 * Response for POST /api/flashcards - Create flashcard
 */
export interface CreateFlashcardResponse {
  data: FlashcardDTO;
}

/**
 * Response for PATCH /api/flashcards/:id - Update flashcard
 */
export interface UpdateFlashcardResponse {
  data: FlashcardDTO;
}

/**
 * Response for DELETE /api/flashcards/:id - Delete flashcard
 */
export interface DeleteFlashcardResponse {
  message: string;
}

/**
 * Response for GET /api/flashcards/count - Get flashcards count
 */
export interface GetFlashcardsCountResponse {
  count: number;
}

/**
 * Response for GET /api/health - Health check endpoint
 */
export interface HealthCheckResponse {
  status: string;
  timestamp: string;
}

/**
 * ============================================================================
 * Command Models - API Request Types
 * ============================================================================
 */

/**
 * Command for creating a new flashcard (POST /api/flashcards).
 *
 * Derived from TablesInsert<'flashcards'> but excludes:
 * - id (auto-generated by database)
 * - user_id (automatically set by database trigger)
 * - created_at (auto-generated by database)
 * - updated_at (auto-generated by database)
 *
 * Only source_text and translation are user-provided.
 */
export type CreateFlashcardCommand = Pick<TablesInsert<"flashcards">, "source_text" | "translation">;

/**
 * Command for updating an existing flashcard (PATCH /api/flashcards/:id).
 *
 * Derived from TablesUpdate<'flashcards'> but excludes:
 * - id (cannot be changed)
 * - user_id (cannot be changed, enforced by database trigger)
 * - created_at (cannot be changed)
 * - updated_at (auto-updated by database)
 *
 * Only source_text and translation can be updated.
 * Both fields are optional - if omitted, existing values are preserved.
 */
export type UpdateFlashcardCommand = Pick<TablesUpdate<"flashcards">, "source_text" | "translation">;

/**
 * Query parameters for listing flashcards (GET /api/flashcards).
 */
export interface ListFlashcardsQuery {
  /**
   * Ordering mode: 'random' (default) or 'id' (ascending by ID)
   * @default 'random'
   */
  order?: "random" | "id";
  /**
   * Maximum number of flashcards to return.
   * Must be a positive integer between 1 and 1000.
   * If not provided, all flashcards are returned.
   */
  limit?: number;
  /**
   * Number of flashcards to skip.
   * Must be a non-negative integer.
   * @default 0
   */
  offset?: number;
}

/**
 * ============================================================================
 * Error Response Types
 * ============================================================================
 */

/**
 * Error code enum for API error responses.
 */
export type ErrorCode = "VALIDATION_ERROR" | "UNAUTHORIZED" | "NOT_FOUND" | "INTERNAL_SERVER_ERROR" | "DATABASE_ERROR";

/**
 * Error details object for validation errors.
 * Structure varies based on the type of validation error.
 */
export type ErrorDetails =
  | {
      field: string;
      max_length?: number;
      actual_length?: number;
    }
  | {
      parameter: string;
      provided_value: string;
      valid_values: string[];
    }
  | Record<string, unknown>;

/**
 * Standard error response structure for all API error responses.
 */
export interface ErrorResponse {
  error: {
    code: ErrorCode;
    message: string;
    details?: ErrorDetails;
  };
}

/**
 * ============================================================================
 * ViewModel Types - Frontend Component Types
 * ============================================================================
 */

/**
 * State for the StudyView component.
 * Manages flashcards, current index, mode, study session, UI state, and dialogs.
 */
export interface StudyViewState {
  // Data
  flashcards: FlashcardDTO[];
  currentIndex: number;

  // Mode
  mode: "browse" | "study";
  isStudySessionActive: boolean;

  // Study session state
  studySession: {
    flashcards: FlashcardDTO[]; // random order
    currentIndex: number;
    completed: Set<string>; // IDs of completed flashcards
  } | null;

  // UI state
  isLoading: boolean;
  error: ErrorResponse | null;

  // Dialogs
  editingFlashcard: FlashcardDTO | null;
  deletingFlashcard: FlashcardDTO | null;

  // Card state
  isCardFlipped: boolean;
}

/**
 * Props for FlashcardsCarousel component.
 */
export interface FlashcardsCarouselProps {
  flashcards: FlashcardDTO[];
  currentIndex: number;
  isCardFlipped: boolean;
  onCardChange: (index: number) => void;
  onCardFlip: () => void;
  onEdit: (flashcard: FlashcardDTO) => void;
  onDelete: (flashcard: FlashcardDTO) => void;
  progress?: {
    current: number;
    total: number;
  };
}

/**
 * Props for FlashcardCard component.
 */
export interface FlashcardCardProps {
  flashcard: FlashcardDTO;
  isFlipped: boolean;
  onFlip: () => void;
  onEdit: () => void;
  onDelete: () => void;
}

/**
 * Props for EditFlashcardDialog component.
 */
export interface EditFlashcardDialogProps {
  flashcard: FlashcardDTO | null;
  onSave: (id: string, data: UpdateFlashcardCommand) => Promise<void>;
  onCancel: () => void;
  isOpen: boolean;
}

/**
 * Props for DeleteFlashcardDialog component.
 */
export interface DeleteFlashcardDialogProps {
  flashcard: FlashcardDTO | null;
  onConfirm: (id: string) => Promise<void>;
  onCancel: () => void;
  isOpen: boolean;
}

/**
 * Props for ErrorDisplay component.
 */
export interface ErrorDisplayProps {
  error: ErrorResponse | null;
  onRetry?: () => void;
}

/**
 * Props for NavigationButtons component.
 */
export interface NavigationButtonsProps {
  hasPrevious: boolean;
  hasNext: boolean;
  onPrevious: () => void;
  onNext: () => void;
}

/**
 * Props for ProgressIndicator component.
 */
export interface ProgressIndicatorProps {
  current: number;
  total: number;
}

/**
 * Props for CharacterCounter component.
 */
export interface CharacterCounterProps {
  current: number;
  max: number;
}
